name: Update parent repository

on:
  pull_request:
    branches: 
      - main
    types:
      - closed

jobs:
  update:
    name: Update Submodule
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    steps:
      - uses: actions/checkout@v4
        with: 
          repository: TrueMoonn/GameOne
          token: ${{ secrets.SUBMODULE_PRIVATE_TOKEN }}
          submodules: true

      - name: Pull & update submodules
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote

      - name: Commit changes
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions - update submodules"
          git add --all
          git commit -m "auto-update(sub-${{github.event.repository.name}}): ${{github.event.pull_request.title}}" || echo "No changes to commit"
          git push
