name: Assurance Project Safety

on:
  pull_request:

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          repository: TrueMoonn/TrueEngine
          token: ${{ secrets.SUBMODULE_PRIVATE_TOKEN }}
          submodules: true

      - name: Install X11 Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          libx11-dev \
          libxrandr-dev \
          libxi-dev \
          libxcursor-dev \
          libxinerama-dev \
          libgl1-mesa-dev


      - name: Fetch Sub-Modules
        run: |
          git submodule update --init --recursive

      - name: Build Project
        run: |
          mkdir build && cd build
          cmake .. -DENABLE_TE_TESTS=ON -DENABLE_TE_COVERAGE=ON
          cmake --build .

      - name: Run Tests
        working-directory: ./build/
        run: ctest --output-on-failure

  coding-style:
    name: Coding Style Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install Cpplint
        run: pip install cpplint

      - name: Run Coding Style
        run: cpplint --recursive .
